version: "3"
services:
  front:
    container_name: front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./app:/var/www/html
    tty: true
    restart: always
